EXTLIB_PATH = $$PWD/3rdparty
ZIP_PATH = $$EXTLIB_PATH/zip/src

SOURCES += $$ZIP_PATH/zip.c
HEADERS += $$ZIP_PATH/zip.h $$ZIP_PATH/miniz.h

INCLUDEPATH += $$ZIP_PATH
DEPENDPATH += $$ZIP_PATH
win32-msvc*:DEFINES += -D_CRT_SECURE_NO_WARNINGS
